services:
   postgres:
      image: postgres:13
      container_name: postgres
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: password
         POSTGRES_DB: spex
         POSTGRES_HOST: localhost
      ports:
         - "5432:5432"
      volumes:
         - postgres_data:/var/lib/postgresql/data
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U user -d spex"]
         interval: 5s
         timeout: 5s
         retries: 5

   prisma-migrate:
      build:
         context: .
         dockerfile: ./packages/prisma/Dockerfile
         args:
            DATABASE_URL: postgresql://user:password@postgres:5432/spex
      container_name: prisma-migrate
      depends_on:
         postgres:
            condition: service_healthy
      command: npx prisma migrate deploy
      

   file-api:
      build:
         context: .
         dockerfile: ./apps/file-api/Dockerfile
         args:
            DATABASE_URL: postgresql://user:password@postgres:5432/spex
      container_name: file-api
      command: sh -c "npm run start:prod"
      ports:
         - "3000:3000"
      depends_on:
         prisma-migrate:
            condition: service_completed_successfully
      environment:
         DATABASE_URL: postgresql://user:password@postgres:5432/spex

   file-processor:
      build:
         context: .
         dockerfile: ./apps/file-processor/Dockerfile
         args:
            DATABASE_URL: postgresql://user:password@postgres:5432/spex
      container_name: file-processor
      command: npm run start:prod
      ports:
         - "3001:3001"
      depends_on:
         prisma-migrate:
            condition: service_completed_successfully
      environment:
         DATABASE_URL: postgresql://user:password@postgres:5432/spex

volumes:
   postgres_data:
